development:
  adapter: postgresql
  database: highscore-development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
test:
  adapter: postgresql
  database: highscoretest
  username: postgres
  password:
  host: localhost
production:
  adapter: postgresql
  database: highscore
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost